export const products=[
  {
  id:'1',
image:"iteams/img42.avif",
name:"Markham Chunky Neoprene Black Shoe",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img42.avif","iteams/img43.avif","iteams/img44.avif","iteams/img45.avif"],
  colour:["black","red","blue","green"],
},
description:"Step out in style with the Markham Chunky Neoprene Black Shoe. Crafted from high-quality PU, these shoes are designed in for durability. With a sleek black design, these shoes offer comfort and style. Get ready to elevate your look with these trendy kicks.",
size:["6","7","8","9"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'2',
image:"iteams/img46.avif",
name:" Markham Men's Walabee PU Front Black Shoe",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img46.avif","iteams/img47.avif"],
  colour:["black"],
},
description:"The Markham Men's Walabee PU Front Black Shoe delivers a refined update to a classic silhouette with subtle brogue detailing and a modern edge. Designed for versatility, it pairs effortlessly with both smart and casual looks.",
size:["6","7","8","9"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'3',
image:"iteams/img48.avif",
name:" Men's Mazerata Black Vinchey 30 Shoes",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img48.avif","iteams/img49.avif","iteams/img50.avif"],
  colour:["black"],
},
description:"Mazerata",
size:["6","7","8","9"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'4',
image:"iteams/img51.avif",
name:" Jonathan D Men's Penny Moc PU Black-White Loafer",
Producttype:'shoes',
price:1000,
album:{
  pictures:["iteams/img51.avif","iteams/img52.avif","iteams/img53.avif"],
  colour:["black"],
},
description:"A master of versatility, this updated  iconic  penny loafer with a moc toe adds a cool edge to any outfit. Resting on a thick rubber-lug sole, sporting mesh lining and anti heel slip for added comfort and wear.",
size:["6","7","8","9"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'5',
image:"iteams/img54.avif",
name:" Markham Men's Brogue Chunky Matte Brown Shoe",
Producttype:'shoes',
price:950,
album:{
  pictures:["iteams/img54.avif","iteams/img55.avif","iteams/img56.avif"],
  colour:["black"],
},
description:"The Markham Men's Brogue Chunky Matte Brown Shoe offers a sophisticated blend of style and comfort. With its distinctive brogue detailing and chunky design, these shoes are perfect for those who appreciate classic elegance.",
size:["6","7","8","9"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'6',
image:"iteams/img57.avif",
name:"Women's Steve Madden Black NEWLYWED Heels",
Producttype:'heels',
price:1800,
album:{
  pictures:["iteams/img57.avif","iteams/img58.avif","iteams/img59.avif","iteams/img60.avif","iteams/img61.avif"],
  colour:["black"],
},
description:"The NEWLYWED heels in black offer a modern take on a classic silhouette. With a stable block heel and elegant design, these Steve Madden shoes provide both style and support for long-lasting wear.",
size:["4","5","6","7"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'7',
image:"iteams/img62.avif",
name:"Foschini Classic Aviator Sunglasses",
Producttype:'shades',
price:200,
album:{
  pictures:["iteams/img62.avif","iteams/img63.avif","iteams/img64.avif","iteams/img65.avif"],
  colour:["black"],
},
size:["adult"],
class:"Premium",
description:"The Foschini Classic Aviator Sunglasses offer a timeless design with a modern twist. These sunglasses provide excellent UV protection while maintaining a stylish appearance that complements any outfit.",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
{
  id:'8',
image:"iteams/img31.avif",
name:"lUX dress",
Producttype:'dress',
price:900,
album:{
  pictures:["iteams/img31.avif","iteams/img32.avif","iteams/img33.avif","iteams/img34.avif","iteams/img35.avif","iteams/img36.avif"],
  colour:["black","red","blue","green"],
},
description:"These formal shoes are the epitome of sophistication and style. Crafted with meticulous attention to detail, they feature a sleek design that effortlessly combines elegance with comfort. The high-quality materials used in their construction ensure durability and a luxurious feel. Whether you're attending a formal event or want to elevate your everyday look, these shoes are the perfect choice to make a lasting impression.",
size:["XS","S","M","L","XL"],
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'9',
image:"iteams/img38.avif",
name:"Makharm shoes",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img38.avif","iteams/img39.avif"],
  colour:["black"],
},
description:"These Makharm shoes are a stylish and comfortable choice for any occasion. With their elegant design and superior quality, they offer both fashion and functionality. Whether you're heading to a casual outing or a more formal event, these shoes will help you make a lasting impression.",
size:["4","5","6","7","8","9","10","11","12"],
class:"Premium",
location:"//https://bash.com/markham-men-s-animal-black-white-loafer-020203acfh6/p",
rentalStatus:"available",
},

{
id:'10',
image:"iteams/img41.avif",
name:"Heart Pendant Necklace",
Producttype:'necklaces',
price:200,
album:{
  pictures:["iteams/img40.avif","iteams/img41.avif"],
  colour:["Gold"],
},
description:"This layered faux pearl and heart pendant necklace blends classic elements with a modern, playful feel — an easy way to elevate simple outfits.",
size:["adult"],
class:"Premium",
location:"https://www.woolworths.co.za/prod/Women/Accessories/Woolworths-Layered-Faux-Pearl-Heart-Pendant-Necklace/_/A-511311154",
rentalStatus:"unavailable",
},
{
id:'11',
image:"iteams/img90.avif",
name:" Press on reusable Nails",
Producttype:'nails',
price:38,
album:{
  pictures:["iteams/img90.avif","iteams/img91.avif","iteams/img92.avif","iteams/img92.avif"],
  colour:["defult"],
},
description:"Set Elegant Gradient Pink & White Almond-Shaped Nail Stickers With 3D Floral & Pearl Decor, Includes Gel Polish And Nail File, Suitable For Girls/Women For Daily, Party, Autumn Nails Nail Supplies",
size:["adult"],
class:"budget",
location:"https://www.woolworths.co.za/prod/Women/Accessories",
rentalStatus:"unavailable",
},
{
  id:'12',
image:"iteams/img4.avif",
name:"Elegant dress",
Producttype:'dresses',
price:1200,
album:{
  pictures:["iteams/img0.avif","iteams/img2.avif","iteams/img3.avif","iteams/img4.avif"],
  colour:["Burgundy"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'13',
image:"iteams/img29.avif",
name:" Elegant Suit",
Producttype:'accesories',
price:50,
album:{
  pictures:["iteams/img29.avif"],
  colour:["defult"],
},
description:"This is a simple",
size:["adult"],
class:"budget",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
{
  id:'14',
image:"iteams/img8.avif",
name:"simple dress",
Producttype:'dresses',
price:840,
album:{
  pictures:["iteams/img8.avif","iteams/img9.avif","iteams/img10.avif"],
  colour:["Red","Blue","Black"],
},
size:["XS","S","M","L","XL"],
class:"Budget",
description:"",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'15',
image:"iteams/img12.avif",
name:" Glam dress",
Producttype:'dresses',
price:1700,
album:{
  pictures:["iteams/img12.avif","iteams/img13.avif","iteams/img14.avif","iteams/img15.avif"],
  colour:["Red"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Elegant Stretch Fabric Heart-shaped Neckline with Bead and Sequin Appliqués, High Thigh-slit on the Side, Formal Evening Gown for Dinner Parties, Weddings, Guest Events, Balls, Receptions, Bachelorette Parties, and Red Carpet Occasions",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'16',
image:"iteams/img16.avif",
name:"Purimine dress",
Producttype:'dresses',
price:2000,
album:{
  pictures:["iteams/img16.avif","iteams/img17.avif","iteams/img18.avif","iteams/img19.avif"],
  colour:["light Blue","Black"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Elegant Light Blue Chest Perspective Three-Dimensional Flower Embroidery Fabric Spliced Mesh Trailing Off-The-Shoulder Dress Suitable for Formal Banquets, Parties, Weddings, And Birthday Parties",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},{
  id:'17',
image:"iteams/img20.avif",
name:"Beaded Fishtail Train Light Luxury Dress",
Producttype:'dresses',
price:1200,
album:{
  pictures:["iteams/img20.avif","iteams/img21.avif","iteams/img22.avif"],
  colour:["Red","Pink"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Red Chest Perspective Three-Dimensional Flower Embroidery Fabric Spliced Mesh Trailing Off-The-Shoulder Dress Suitable for Formal Banquets, Parties, Weddings, And Birthday Parties",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'18',
image:"iteams/img66.avif",
name:" Elenzga women elegant office suit",
Producttype:'suits',
price:431,
album:{
  pictures:["iteams/img66.avif","iteams/img67.avif","iteams/img68.avif","iteams/img69.avif"],
  colour:["black","burgundy"],
},
description:"Elenzga Women Elegant Office Pants Suit,Fall Winter Commute Irregular Crossed Collar Blazer & Lantern Sleeve Shirt,Elastic Waist A-Line Flare Pants",
size:["XS","S","M","L","XL"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'19',
image:"iteams/img70.avif",
name:"Beaded Fishtail Train Light Luxury Dress",
Producttype:'dresses',
price:2632,
album:{
  pictures:["iteams/img70.avif","iteams/img71.avif"],
  colour:["Navy Blue"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Navy Blue Off Shoulder Sequin Evening Dress, Lace Waist Trim Maxi Gown, Women's Banquet & Wedding Guest Dress Party",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'20',
image:"iteams/img73.avif",
name:"Women Prom Dresses",
Producttype:'dresses',
price:1715,
album:{
  pictures:["iteams/img73.avif","iteams/img74.avif","iteams/img72.avif"],
  colour:["Navy Blue","Black","Red"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Women Prom Dresses, Elegant Formal Evening Gown, For Wedding Guest, Graduation, Dinner Party Dress Spring",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'21',
image:"iteams/img75.avif",
name:"VIPGIRL loral Off-Shoulder Sheer Prom Dress",
Producttype:'dresses',
price:1278,
album:{
  pictures:["iteams/img75.avif","iteams/img76.avif","iteams/img77.avif"],
  colour:["Navy Blue","white","Red"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"VIPGIRL SHannah Dreamy Blue Floral Off-Shoulder Sheer Prom Dress, High Slit Design, Fitted Bodice, Princess Style Long Gown, Women's Formal Evening Dress, Elegant Party Dress, Wedding Guest Dress Spring",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'22',
image:"iteams/img78.avif",
name:"VIPGIRL loral Off-Shoulder Sheer Prom Dress",
Producttype:'dresses',
price:1400,
album:{
  pictures:["iteams/img78.avif","iteams/img79.avif","iteams/img80.avif"],
  colour:["Navy Blue","Black","Red"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Aureia Elegant Burgundy Jacquard Backless Halter-Neck A-Line Dress, Stylish Evening Gown For Wedding,Graduation,Birthday Party,Dance & Music Festival",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'23',
image:"iteams/img81.avif",
name:"Beaded Shoulder Bowknot Dress",
Producttype:'dresses',
price:969,
album:{
  pictures:["iteams/img81.avif","iteams/img82.avif","iteams/img83.avif"],
  colour:["Navy Blue","Black","Red"],
},
size:["XS","S","M","L","XL"],
class:"Budget",
description:"Belle Gorgeous Beaded Shoulder Bowknot Dress For Women's Formal Evening Party Dress Elegant Prom Wedding Guest Gown, For Graduation, Dinner",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'25',
image:"iteams/img84.avif",
name:" Women High Heel ",
Producttype:'heels',
price:310,
album:{
  pictures:["iteams/img84.avif","iteams/img85.avif","iteams/img86.avif"],
  colour:["silver"],
},
size:["4","5","6","7","8",],
class:"Budget",
description:"Fashion Women High Heel Shoes: Metal PU Leather Anti-Explosion Strap Flat Sandals;",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'26',
image:"iteams/img87.avif",
name:"Roman Style Faux",
Producttype:'heels',
price:310,
album:{
  pictures:["iteams/img87.avif","iteams/img88.avif","iteams/img89.avif"],
  colour:["Black"],
},
size:["4","5","6","7","8",],
class:"Budget",
description:"Women's Roman Style Faux Fur Chunky Heel Black Party Sandals, Women's Platform High Heel Shoes",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'27',
image:"iteams/img96.avif",
name:"Mini Hat And Feather Accessory",
Producttype:'hats',
price:310,
album:{
  pictures:["iteams/img96.avif","iteams/img97.avif","iteams/img98.avif"],
  colour:["Black","Red","Blue"],
},
size:["Adult"],
class:"Budget",
description:"1set Women's Classic Fashion Faux Pearls Necklace, Lace Gloves, Hair Clip, Mini Hat And Feather Accessory",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'28',
image:"iteams/img99.avif",
name:"Caramel 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img99.avif"],
  colour:["Caramel"],
},
size:["36","38","40","42","44","46","48"],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'30',
image:"iteams/img100.avif",
name:"Black 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img100.avif"],
  colour:["Black"],
},
size:["36","38","40","42","44","46","48"],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'31',
image:"iteams/img101.avif",
name:"Navy Blue 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img101.avif"],
  colour:["Navy Blue"],
},
size:["36","38","40","42","44","46","48"],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'32',
image:"iteams/img103.avif",
name:" Grey 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img103.avif"],
  colour:["Grey"],
},
size:["36","38","40","42","44","46","48 "],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'33',
image:"iteams/img104.avif",
name:" Blue 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img104.avif"],
  colour:["Blue"],
},
size:["36","38","40","42","44","46","48 "],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'34',
image:"iteams/img105.avif",
name:" Sky Blue 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img105.avif"],
  colour:["Sky Blue"],
},
size:["36","38","40","42","44","46","48 "],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'35',
image:"iteams/img106.avif",
name:" Light Beige 3 piece suit",
Producttype:'suits',
price:1000,
album:{
  pictures:["iteams/img106.avif"],
  colour:["light beige"],
},
size:["36","38","40","42","44","46","48 "],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'36',
image:"iteams/img107.avif",
name:"Woolworths Double Chunky Hoop Earrings",
Producttype:'earings',
price:99,
album:{
  pictures:["iteams/img107.avif","iteams/img108.avif","iteams/img109.avif","iteams/img110.avif","iteams/img111.avif","iteams/img112.avif"],
  colour:["silver","Gold"],
},
size:["24mm"],
class:"Budget",
description:"Elevate your presence with this distinguished three-piece suit, designed for those who value sophistication and modern elegance. The tailored blazer and waistcoat create a sleek, structured silhouette, complemented by a crisp dress shirt for a polished finish. A diagonally striped tie adds a bold accent, striking the perfect balance between authority and refinement.",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
{
  id:'37',
image:"iteams/img113.avif",
name:"Golden Butterfly Earrings",
Producttype:'earings',
price:23,
album:{
  pictures:["iteams/img113.avif","iteams/img114.avif"],
  colour:["silver","Gold"],
},
size:["24mm"],
class:"Budget",
description:"3 Pairs of Exquisite Golden Butterfly Design Stud Earrings with Sparkling Synthetic Zirconia Decoration, Y2K Style Alloy Earrings - Gift for Women",
rentalStatus:"unavailable",
},
{
  id:'38',
image:"iteams/img115.avif",
name:"Earrings",
Producttype:'earings',
price:30,
album:{
  pictures:["iteams/img115.avif","iteams/img116.avif"],
  colour:["silver","Gold"],
},
size:["24mm"],
class:"Budget",
description:"A Set of 30 Stylish Heart-Shaped Letter Stud Earrings",
rentalStatus:"unavailable",
},
{
  id:'39',
image:"iteams/img117.avif",
name:"American Clutch Bag",
Producttype:'handbags',
price:150,
album:{
  pictures:["iteams/img117.avif","iteams/img118.avif","iteams/img119.avif","iteams/img120.avif"],
  colour:["silver","Gold","Black"],
},
size:["default"],
class:"Budget",
description:"New High-End Banquet Bag/Dress Versatile European And American Clutch Bag/Crossbody Celebrity Fashion Diamond-Encrusted Butterfly Knot Bag/Wedding Season Mother's Day Gift/Very Suitable for Weddings,",
rentalStatus:"available",
},
{
  id:'40',
image:"iteams/img121.avif",
name:"Sparkling Bow Tote Bag,",
Producttype:'handbags',
price:180,
album:{
  pictures:["iteams/img121.avif","iteams/img122.avif","iteams/img123.avif"],
  colour:["silver","Black"],
},
size:["default"],
class:"Budget",
description:"2025 New Sparkling Silvery Bow Tote Bag, Featuring Multi-Functional Ways of Carrying: Shoulder, Cross-Body, And Hand-Held. It Is Suitable for Formal Occasions, Parties, Weddings, And Daily Use",
rentalStatus:"available",
},
{
  id:'41',
image:"iteams/img124.avif",
name:"Crown Chain Brooch",
Producttype:'accesories',
price:22,
album:{
  pictures:["iteams/img124.avif","iteams/img125.avif","iteams/img126.avif","iteams/img127.avif"],
  colour:["silver","Gold"],
},
size:["default"],
class:"Budget",
description:"1pc Crown Chain Brooch/Studded with Rhinestones/Suit Pin/Accessory for Weddings, Parties, and Formal Occasions/Unique and Exquisite Gift",
rentalStatus:"unavailable",
},
{
  id:'42',
image:"iteams/img128.avif",
name:"Arm Cuff",
Producttype:'accesories',
price:22,
album:{
  pictures:["iteams/img129.avif","iteams/img130.avif","iteams/img128.avif"],
  colour:["silver","Gold"],
},
size:["default"],
class:"Budget",
description:"1 Minimalist Geometric Butterfly Women'S Fashion Arm Cuff",
rentalStatus:"available",
},
{
  id:'43',
image:"iteams/img131.avif",
name:"Short Straight Full Frontal ",
Producttype:'frontals',
price:450,
album:{
  pictures:["iteams/img131.avif","iteams/img132.avif","iteams/img133.avif","iteams/img134.avif"],
  colour:["Black"],
},
size:["10inch"],
class:"Budget",
description:"10 Inch Bob Wig13X4 Lace Front Wigs Short Straight Full Frontal Wig Bob Cut",
rentalStatus:"unavailable",
},
{
  id:'44',
image:"iteams/img134.avif",
name:"Glueless Straight Wig Golden Perfect",
Producttype:'frontals',
price:600,
album:{
  pictures:["iteams/img134.avif","iteams/img135.avif","iteams/img136.avif"],
  colour:["Black"],
},
size:["8inch","10inch","12inch","14inch"],
class:"Budget",
description:"100% human hair,Factory Price ,Straight Human Hair Ear to Ear Lace Frotnal Wigs Golden Perfect",
rentalStatus:"available",
},
];

