export const products=[{
id:'1',
image:"iteams/img2.avif",
name:"Elegant Dress",
Producttype:'dress',
price:900,
album:{
  pictures:[],
  colour:[],
},
description:"This elegant dress is a timeless piece that exudes sophistication and grace. Crafted with meticulous attention to detail, it features a flattering silhouette that enhances your natural beauty. The luxurious fabric drapes beautifully, creating a stunning and elegant look for any special occasion. Whether you're attending a formal event or a glamorous party, this dress will make you feel confident and radiant, ensuring you stand out in style.",
size:["XS","S","M","L","XL"],
// Here must be the link to their provider if its available if not i should specify how will i get this products 
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'2',
image:"iteams/img3.avif",
name:"Brazilian",
Producttype:'frontals',
price:300,
album:{
  pictures:[],
  colour:["defult"],
},
description:"This Brazilian frontal is a high-quality hairpiece designed to provide a natural and seamless look. Made from 100% Brazilian human hair, it offers versatility in styling and can be dyed, curled, or straightened to suit your preferences. The frontal is crafted with meticulous attention to detail, featuring a lace base that mimics the appearance of a natural scalp. Whether you're looking to add volume, length, or simply want to change up your hairstyle, this Brazilian frontal is a fantastic choice for achieving a flawless and realistic look.",
size:["30cm","50cm","60cm","70cm","80cm"],
///sdrtrfgyuhijokpokijhggcfhbjj
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'3',
image:"iteams/img5.avif",
name:"Glam Dress",
Producttype:'dresses',
price:1200,
album:{
  pictures:["iteams/img5.avif","iteams/img0.avif"],
  colour:[],
},
description:"This Glam Dress is a high-quality garment designed to provide a natural and seamless look. Made from 100% premium fabric, it offers versatility in styling and can be dyed, curled, or straightened to suit your preferences. The dress is crafted with meticulous attention to detail, featuring a lace base that mimics the appearance of a natural scalp. Whether you're looking to add volume, length, or simply want to change up your hairstyle, this Glam Dress is a fantastic choice for achieving a flawless and realistic look.",
size:["XS","S","M","L","XL"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'4',
image:"iteams/img4.avif",
name:"Lux handbag",
Producttype:'handbags',
price:400,
album:{
  pictures:[],
  colour:[],
},
description:"This Lux handbag is a stunning and sophisticated choice for any special occasion. Crafted with meticulous attention to detail, it features a luxurious fabric that drapes elegantly on the body. The handbag is designed to enhance your silhouette, with a flattering fit and exquisite embellishments that add a touch of glamour. Whether you're attending a formal event or a glamorous party, this Lux handbag will make you feel confident and radiant, ensuring you stand out in style.",
size:["defult"],
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
{
id:'5',
image:"iteams/img10.avif",
name:"Tall girl heels",
Producttype:'heels',
price:350,
album:{
  pictures:[],
  colour:["defualt"],
},
description:"These tall girl heels are a stylish and comfortable choice for any occasion. With their elegant design and superior quality, they offer both fashion and functionality. Whether you're heading to a casual outing or a more formal event, these heels will help you make a lasting impression.",
size:["4","5","6","7","8","9","10","11","12"],
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{id:'6',
image:"iteams/img9.avif",
name:"Butterfly heels",
Producttype:'heels',
price:400,
album:{
  pictures:[],
  colour:[],
},
description:"These butterfly heels are a stunning and whimsical addition to any footwear collection. Featuring delicate butterfly embellishments, these heels exude a sense of grace and femininity. The intricate design and attention to detail make them a standout choice for special occasions or when you want to add a touch of enchantment to your outfit. With their unique and eye-catching style, these butterfly heels are sure to make a statement wherever you go.",
size:["4","5","6","7","8","9","10","11","12"],
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},{
  id:'7',
image:"iteams/img20.avif",
name:"Formal shoes",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img20.avif","iteams/img21.avif","iteams/img22.avif","iteams/img23.avif","iteams/img24.avif","iteams/img25.avif","iteams/img26.avif"],
  colour:[],
},
description:"These formal shoes are the epitome of sophistication and style. Crafted with meticulous attention to detail, they feature a sleek design that effortlessly combines elegance with comfort. The high-quality materials used in their construction ensure durability and a luxurious feel. Whether you're attending a formal event or want to elevate your everyday look, these shoes are the perfect choice to make a lasting impression.",
size:["4","5","6","7","8","9","10","11","12"],
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'8',
image:"iteams/img31.avif",
name:"lUX dress",
Producttype:'dress',
price:900,
album:{
  pictures:["iteams/img31.avif","iteams/img32.avif","iteams/img33.avif","iteams/img34.avif","iteams/img35.avif","iteams/img36.avif"],
  colour:["black","red","blue","green"],
},
description:"These formal shoes are the epitome of sophistication and style. Crafted with meticulous attention to detail, they feature a sleek design that effortlessly combines elegance with comfort. The high-quality materials used in their construction ensure durability and a luxurious feel. Whether you're attending a formal event or want to elevate your everyday look, these shoes are the perfect choice to make a lasting impression.",
size:["XS","S","M","L","XL"],
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'9',
image:"iteams/img38.avif",
name:"Makharm shoes",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img38.avif","iteams/img39.avif"],
  colour:["black"],
},
description:"These Makharm shoes are a stylish and comfortable choice for any occasion. With their elegant design and superior quality, they offer both fashion and functionality. Whether you're heading to a casual outing or a more formal event, these shoes will help you make a lasting impression.",
size:["4","5","6","7","8","9","10","11","12"],
class:"Premium",
location:"//https://bash.com/markham-men-s-animal-black-white-loafer-020203acfh6/p",
rentalStatus:"available",
},

{
id:'10',
image:"iteams/img41.avif",
name:"Heart Pendant Necklace",
Producttype:'necklaces',
price:200,
album:{
  pictures:["iteams/img40.avif","iteams/img41.avif"],
  colour:["Gold"],
},
description:"This layered faux pearl and heart pendant necklace blends classic elements with a modern, playful feel — an easy way to elevate simple outfits.",
size:["adult"],
class:"Premium",
location:"https://www.woolworths.co.za/prod/Women/Accessories/Woolworths-Layered-Faux-Pearl-Heart-Pendant-Necklace/_/A-511311154",
rentalStatus:"unavailable",
},
{
id:'11',
image:"iteams/img22.avif",
name:" Pendant Nails",
Producttype:'nails',
price:30,
album:{
  pictures:["iteams/img22.avif","iteams/img23.avif"],
  colour:["defult"],
},
description:"This is a simple nail design.",
size:["adult"],
class:"budget",
location:"https://www.woolworths.co.za/prod/Women/Accessories",
rentalStatus:"unavailable",
},
{
id:'12',
image:"iteams/img12.avif",
name:" Elegant Suit",
Producttype:'suits',
price:850,
album:{
  pictures:["iteams/img12.avif","iteams/img14.avif"],
  colour:["Black","Brown"],
},
description:"This is a simple",
size:["S","M","L"],
class:"budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'13',
image:"iteams/img29.avif",
name:" Elegant Suit",
Producttype:'accesories',
price:50,
album:{
  pictures:["iteams/img29.avif"],
  colour:["defult"],
},
description:"This is a simple",
size:["adult"],
class:"budget",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
];