export const products=[
  {
  id:'1',
image:"iteams/img42.avif",
name:"Markham Chunky Neoprene Black Shoe",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img42.avif","iteams/img43.avif","iteams/img44.avif","iteams/img45.avif"],
  colour:["black","red","blue","green"],
},
description:"Step out in style with the Markham Chunky Neoprene Black Shoe. Crafted from high-quality PU, these shoes are designed in for durability. With a sleek black design, these shoes offer comfort and style. Get ready to elevate your look with these trendy kicks.",
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'2',
image:"iteams/img46.avif",
name:" Markham Men's Walabee PU Front Black Shoe",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img46.avif","iteams/img47.avif"],
  colour:["black"],
},
description:"The Markham Men's Walabee PU Front Black Shoe delivers a refined update to a classic silhouette with subtle brogue detailing and a modern edge. Designed for versatility, it pairs effortlessly with both smart and casual looks.",
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'3',
image:"iteams/img48.avif",
name:" Men's Mazerata Black Vinchey 30 Shoes",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img48.avif","iteams/img49.avif","iteams/img50.avif"],
  colour:["black"],
},
description:"Mazerata",
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'4',
image:"iteams/img51.avif",
name:" Jonathan D Men's Penny Moc PU Black-White Loafer",
Producttype:'shoes',
price:1000,
album:{
  pictures:["iteams/img51.avif","iteams/img52.avif","iteams/img53.avif"],
  colour:["black"],
},
description:"A master of versatility, this updated  iconic  penny loafer with a moc toe adds a cool edge to any outfit. Resting on a thick rubber-lug sole, sporting mesh lining and anti heel slip for added comfort and wear.",
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'5',
image:"iteams/img54.avif",
name:" Markham Men's Brogue Chunky Matte Brown Shoe",
Producttype:'shoes',
price:950,
album:{
  pictures:["iteams/img54.avif","iteams/img55.avif","iteams/img56.avif"],
  colour:["black"],
},
description:"The Markham Men's Brogue Chunky Matte Brown Shoe offers a sophisticated blend of style and comfort. With its distinctive brogue detailing and chunky design, these shoes are perfect for those who appreciate classic elegance.",
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'6',
image:"iteams/img57.avif",
name:"Women's Steve Madden Black NEWLYWED Heels",
Producttype:'heels',
price:1800,
album:{
  pictures:["iteams/img57.avif","iteams/img58.avif","iteams/img59.avif","iteams/img60.avif","iteams/img61.avif"],
  colour:["black"],
},
description:"The NEWLYWED heels in black offer a modern take on a classic silhouette. With a stable block heel and elegant design, these Steve Madden shoes provide both style and support for long-lasting wear.",
class:"Premium",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'7',
image:"iteams/img62.avif",
name:"Foschini Classic Aviator Sunglasses",
Producttype:'shades',
price:1800,
album:{
  pictures:["iteams/img62.avif","iteams/img63.avif","iteams/img64.avif","iteams/img65.avif"],
  colour:["black"],
},
class:"Premium",
description:"The Foschini Classic Aviator Sunglasses offer a timeless design with a modern twist. These sunglasses provide excellent UV protection while maintaining a stylish appearance that complements any outfit.",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
{
  id:'8',
image:"iteams/img31.avif",
name:"lUX dress",
Producttype:'dress',
price:900,
album:{
  pictures:["iteams/img31.avif","iteams/img32.avif","iteams/img33.avif","iteams/img34.avif","iteams/img35.avif","iteams/img36.avif"],
  colour:["black","red","blue","green"],
},
description:"These formal shoes are the epitome of sophistication and style. Crafted with meticulous attention to detail, they feature a sleek design that effortlessly combines elegance with comfort. The high-quality materials used in their construction ensure durability and a luxurious feel. Whether you're attending a formal event or want to elevate your everyday look, these shoes are the perfect choice to make a lasting impression.",
size:["XS","S","M","L","XL"],
class:"Budget",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'9',
image:"iteams/img38.avif",
name:"Makharm shoes",
Producttype:'shoes',
price:900,
album:{
  pictures:["iteams/img38.avif","iteams/img39.avif"],
  colour:["black"],
},
description:"These Makharm shoes are a stylish and comfortable choice for any occasion. With their elegant design and superior quality, they offer both fashion and functionality. Whether you're heading to a casual outing or a more formal event, these shoes will help you make a lasting impression.",
size:["4","5","6","7","8","9","10","11","12"],
class:"Premium",
location:"//https://bash.com/markham-men-s-animal-black-white-loafer-020203acfh6/p",
rentalStatus:"available",
},

{
id:'10',
image:"iteams/img41.avif",
name:"Heart Pendant Necklace",
Producttype:'necklaces',
price:200,
album:{
  pictures:["iteams/img40.avif","iteams/img41.avif"],
  colour:["Gold"],
},
description:"This layered faux pearl and heart pendant necklace blends classic elements with a modern, playful feel — an easy way to elevate simple outfits.",
size:["adult"],
class:"Premium",
location:"https://www.woolworths.co.za/prod/Women/Accessories/Woolworths-Layered-Faux-Pearl-Heart-Pendant-Necklace/_/A-511311154",
rentalStatus:"unavailable",
},
{
id:'11',
image:"iteams/img22.avif",
name:" Pendant Nails",
Producttype:'nails',
price:30,
album:{
  pictures:["iteams/img22.avif","iteams/img23.avif"],
  colour:["defult"],
},
description:"This is a simple nail design.",
size:["adult"],
class:"budget",
location:"https://www.woolworths.co.za/prod/Women/Accessories",
rentalStatus:"unavailable",
},
{
  id:'12',
image:"iteams/img4.avif",
name:"Elegant dress",
Producttype:'dresses',
price:1200,
album:{
  pictures:["iteams/img0.avif","iteams/img2.avif","iteams/img3.avif","iteams/img4.avif"],
  colour:["Burgundy"],
},
class:"Premium",
description:"",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
id:'13',
image:"iteams/img29.avif",
name:" Elegant Suit",
Producttype:'accesories',
price:50,
album:{
  pictures:["iteams/img29.avif"],
  colour:["defult"],
},
description:"This is a simple",
size:["adult"],
class:"budget",
location:"https://www.woolworths.co.za",
rentalStatus:"unavailable",
},
{
  id:'14',
image:"iteams/img8.avif",
name:"simple dress",
Producttype:'dresses',
price:840,
album:{
  pictures:["iteams/img8.avif","iteams/img9.avif","iteams/img10.avif"],
  colour:["Red","Blue","Black"],
},
size:["XS","S","M","L","XL"],
class:"Budget",
description:"",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'15',
image:"iteams/img12.avif",
name:" Glam dress",
Producttype:'dresses',
price:1700,
album:{
  pictures:["iteams/img12.avif","iteams/img13.avif","iteams/img14.avif","iteams/img15.avif"],
  colour:["Red"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Elegant Stretch Fabric Heart-shaped Neckline with Bead and Sequin Appliqués, High Thigh-slit on the Side, Formal Evening Gown for Dinner Parties, Weddings, Guest Events, Balls, Receptions, Bachelorette Parties, and Red Carpet Occasions",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
{
  id:'16',
image:"iteams/img16.avif",
name:"Purimine dress",
Producttype:'dresses',
price:2000,
album:{
  pictures:["iteams/img16.avif","iteams/img17.avif","iteams/img18.avif","iteams/img19.avif"],
  colour:["light Blue","Black"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"Elegant Light Blue Chest Perspective Three-Dimensional Flower Embroidery Fabric Spliced Mesh Trailing Off-The-Shoulder Dress Suitable for Formal Banquets, Parties, Weddings, And Birthday Parties",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},{
  id:'17',
image:"iteams/img20.avif",
name:"Beaded Fishtail Train Light Luxury Dress",
Producttype:'dresses',
price:1200,
album:{
  pictures:["iteams/img20.avif","iteams/img21.avif","iteams/img22.avif"],
  colour:["Red","Pink"],
},
size:["XS","S","M","L","XL"],
class:"Premium",
description:"",
location:"https://www.woolworths.co.za",
rentalStatus:"available",
},
];